apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
spec:
  type: ClusterIP  # Specifies the type of Service
  selector:
    app: postgres  # Selects the pods with label app=postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432