apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ml
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50