apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gate
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gate
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50