apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dc
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50