apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: userapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userapi
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50