apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50